/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.HoKhauModel;
import Controller.HoKhauController;
import Model.NhanKhauModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThinkKING
 */
public class HoKhauView extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form HoKhauView
     */
    HoKhauController dao = new HoKhauController();
    String strFind = "";
    String strID = "";

    public HoKhauView() {
        initComponents();
        setTitle("Trang chủ Hộ Khẩu");
        fillTable();
        setLocationRelativeTo(null);
        addHoKhaubtn.addActionListener(this);
        updateHoKhaubtn.addActionListener(this);
        delHoKhaubtn.addActionListener(this);
        BacktoHomePagebtn.addActionListener(this);
    }

    public void fillTable() {
        DefaultTableModel tbModel = (DefaultTableModel) TableHK.getModel();
        tbModel.setRowCount(0); // Xoa data trong table
        Object dataRow[] = new Object[5];
        for (HoKhauModel hk : dao.getAll()) {
          
            dataRow[0] = hk.getMaHo();
            dataRow[1] = hk.getIDChuHo();
            dataRow[2] = hk.getSoThanhvien();
            dataRow[3] = hk.getDiaChi();
            tbModel.addRow(dataRow); // add du lieu vao table Model
        }
      
        
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BacktoHomePagebtn = new javax.swing.JButton();
        addHoKhaubtn = new javax.swing.JButton();
        updateHoKhaubtn = new javax.swing.JButton();
        delHoKhaubtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHK = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        BacktoHomePagebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/home (1).png"))); // NOI18N

        addHoKhaubtn.setBackground(new java.awt.Color(204, 51, 0));
        addHoKhaubtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addHoKhaubtn.setForeground(new java.awt.Color(255, 255, 255));
        addHoKhaubtn.setText("THÊM");

        updateHoKhaubtn.setBackground(new java.awt.Color(204, 51, 0));
        updateHoKhaubtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateHoKhaubtn.setForeground(new java.awt.Color(255, 255, 255));
        updateHoKhaubtn.setText("CẬP NHẬT");
        updateHoKhaubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateHoKhaubtnActionPerformed(evt);
            }
        });

        delHoKhaubtn.setBackground(new java.awt.Color(204, 51, 0));
        delHoKhaubtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delHoKhaubtn.setForeground(new java.awt.Color(255, 255, 255));
        delHoKhaubtn.setText("Xóa");
        delHoKhaubtn.setToolTipText("");
        delHoKhaubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delHoKhaubtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BacktoHomePagebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addHoKhaubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateHoKhaubtn, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(delHoKhaubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BacktoHomePagebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(addHoKhaubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateHoKhaubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delHoKhaubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        TableHK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hộ", "Tên Chủ Hộ", "Số Thành Viên", "Địa chỉ"
            }
        ));
        TableHK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableHK);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tìm kiếm theo Tên:");

        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1000, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void delHoKhaubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delHoKhaubtnActionPerformed
        // TODO add your handling code here:
        if (strID.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hộ khẩu để xóa");
        } else {
            if (dao.delHoKhau(Integer.parseInt(strID)) > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                fillTable();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_delHoKhaubtnActionPerformed

    private void TableHKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHKMouseClicked
        // TODO add your handling code here:
        int position = TableHK.rowAtPoint(evt.getPoint());
        strID = TableHK.getValueAt(position, 0).toString();
    }//GEN-LAST:event_TableHKMouseClicked

    private void updateHoKhaubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateHoKhaubtnActionPerformed
        // TODO add your handling code here:
        new EditHoKhauView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateHoKhaubtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoKhauView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BacktoHomePagebtn;
    private javax.swing.JTable TableHK;
    private javax.swing.JButton addHoKhaubtn;
    private javax.swing.JButton delHoKhaubtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JButton updateHoKhaubtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(addHoKhaubtn)) {
            addHoKhauclick();
        } else if (e.getSource().equals(BacktoHomePagebtn)) {
            backtoHomePageClick();
        } else if (e.getSource().equals(delHoKhaubtn)) 
      {    
          delHoKhauclick();
      }
    }
      
    
     

    public void addHoKhauclick() {
        new AddHoKhauView().setVisible(true);
        this.dispose();
    }

    public void backtoHomePageClick() {
        new TrangChuView().setVisible(true);
        this.dispose();
    }

    public void delHoKhauclick() {

    }

}
