/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.KhoanThuController;
import Model.KhoanThuModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinkKING
 */
public class KhoanThuView extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form KhoanThuView
     */
    
    KhoanThuController dao = new KhoanThuController();
    String strFind ="";
    String strID ="";
    private int selectedIndex;
    
    public KhoanThuView() {
        initComponents();
        setTitle("Trang chủ khoản thu");
        fillTable();
        setLocationRelativeTo(null);
        addKhoanThubtn.addActionListener(this);
        delKhoanThubtn.addActionListener(this);
        editKhoanThubtn.addActionListener(this);
        BacktoHomePagebtn.addActionListener(this);
    }
    
    public void fillTable()
    {
        DefaultTableModel tbModel = (DefaultTableModel) TableKT.getModel();
        tbModel.setRowCount(0); // Xoa data trong table
        for(KhoanThuModel kt : dao.findKhoanThuModelbyName(strFind))
        {
            Object dataRow[] = new Object[5];
            dataRow[0] = kt.getMaKhoanThu();
            dataRow[1] = kt.getTenKhoanThu();
            dataRow[2] = kt.getSoTien();
            dataRow[3] = kt.getLoaiKhoanThu();
            tbModel.addRow(dataRow); // add du lieu vao table Model
        }
    }
        
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BacktoHomePagebtn = new javax.swing.JButton();
        addKhoanThubtn = new javax.swing.JButton();
        delKhoanThubtn = new javax.swing.JButton();
        editKhoanThubtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableKT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        BacktoHomePagebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/home (1).png"))); // NOI18N

        addKhoanThubtn.setBackground(new java.awt.Color(204, 51, 0));
        addKhoanThubtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addKhoanThubtn.setForeground(new java.awt.Color(255, 255, 255));
        addKhoanThubtn.setText("THÊM");

        delKhoanThubtn.setBackground(new java.awt.Color(204, 51, 0));
        delKhoanThubtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delKhoanThubtn.setForeground(new java.awt.Color(255, 255, 255));
        delKhoanThubtn.setText("XÓA");
        delKhoanThubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delKhoanThubtnActionPerformed(evt);
            }
        });

        editKhoanThubtn.setBackground(new java.awt.Color(204, 51, 0));
        editKhoanThubtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editKhoanThubtn.setForeground(new java.awt.Color(255, 255, 255));
        editKhoanThubtn.setText("CẬP NHẬT");
        editKhoanThubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editKhoanThubtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BacktoHomePagebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addKhoanThubtn, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(delKhoanThubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editKhoanThubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BacktoHomePagebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(addKhoanThubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editKhoanThubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delKhoanThubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jLabel1.setText("Tìm kiếm theo Tên khoản thu:");

        tfSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfSearchCaretUpdate(evt);
            }
        });
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        TableKT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Khoản Thu", "Tên Khoản Thu", "Số Tiền", "Loại Khoản Thu"
            }
        ));
        TableKT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableKTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableKT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableKTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableKTMouseClicked
        int position = TableKT.rowAtPoint(evt.getPoint());
        strID = TableKT.getValueAt(position, 0).toString();
    }//GEN-LAST:event_TableKTMouseClicked

    private void delKhoanThubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delKhoanThubtnActionPerformed
        // TODO add your handling code here:
        if(strID.equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sinh viên để xóa");
        }else{
            if(dao.delKhoanThu(Integer.parseInt(strID))>0)
            {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            fillTable();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_delKhoanThubtnActionPerformed

    private void editKhoanThubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editKhoanThubtnActionPerformed
        // TODO add your handling code here:
        selectedIndex = TableKT.getSelectedRow();
        if(dao.getAllKhoanThu().size() == 0){
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập thêm khoản thu cần sửa" );
        }
        else if(selectedIndex  == -1){
            JOptionPane.showMessageDialog(rootPane,"Hãy chọn khoản thu cần sửa");
        }
        else{
            EditKhoanThuView edit = new EditKhoanThuView();
            edit.setEditData(dao.getAllKhoanThu().get(selectedIndex));
            edit.setVisible(true);
            this.dispose();
       }
        
    }//GEN-LAST:event_editKhoanThubtnActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_tfSearchActionPerformed

    private void tfSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfSearchCaretUpdate
        // TODO add your handling code here:
       strFind = tfSearch.getText();
       fillTable();
    }//GEN-LAST:event_tfSearchCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoanThuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoanThuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoanThuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoanThuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhoanThuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BacktoHomePagebtn;
    private javax.swing.JTable TableKT;
    private javax.swing.JButton addKhoanThubtn;
    private javax.swing.JButton delKhoanThubtn;
    private javax.swing.JButton editKhoanThubtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(addKhoanThubtn))
      {
          addKhoanThuclick();
      }
      else if(e.getSource().equals(BacktoHomePagebtn))
      {
          backtoHomePageClick();
      }
    }
    public void addKhoanThuclick(){
        new AddKhoanThuView().setVisible(true);
        this.dispose();
    }
    
    public void backtoHomePageClick(){
        new TrangChuView().setVisible(true);
        this.dispose();
    }
}
