/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.NhanKhauController;
import Controller.QuanHeController;
import Model.NhanKhauModel;
import Model.QuanHeModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import View.EditNhanKhauView;
/**
 *
 * @author ThinkKING
 */
public class NhanKhauView extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form NhanKhauView
     */
    NhanKhauController dao = new NhanKhauController();
    QuanHeController daoQH = new QuanHeController();
    String strFind ="";
    String strID ="";
    private int selectedIndex;
    
    public NhanKhauView() {
        initComponents();
        fillTable();
        setLocationRelativeTo(null);
        addNhanKhaubtn.addActionListener(this);
        delNhanKhaubtn.addActionListener(this);
        BacktoHomePagebtn.addActionListener(this);
        
     
    }
    
    public void fillTable()
    {
        DefaultTableModel tbModel = (DefaultTableModel) TableNK.getModel();
        tbModel.setRowCount(0); // Xoa data trong table
        Object dataRow[] = new Object[8];
        for(NhanKhauModel nk : dao.findNhanKhauModelbyName(strFind))
        {
            dataRow[0] = nk.getId();
            dataRow[1] = nk.getTen();
            dataRow[2] = nk.getTuoi();
            dataRow[3] = nk.getCmnd();
            dataRow[4] = nk.getSdt();
            tbModel.addRow(dataRow); // add du lieu vao table Model
        }
       
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BacktoHomePagebtn = new javax.swing.JButton();
        delNhanKhaubtn = new javax.swing.JButton();
        editNhanKhaubtn = new javax.swing.JButton();
        addNhanKhaubtn = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNK = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jButton9.setText("Cập nhật nhân khẩu");

        jButton8.setText("Xóa nhân khẩu");

        jButton7.setText("Thêm nhân khẩu");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Back to Home");
        jButton1.setToolTipText("");

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Nhân Khẩu");

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Hộ Khẩu");

        jButton4.setBackground(new java.awt.Color(51, 102, 255));
        jButton4.setText("Khoản phí");

        jButton5.setBackground(new java.awt.Color(51, 102, 255));
        jButton5.setText("Đóng phí");

        jButton6.setBackground(new java.awt.Color(51, 102, 255));
        jButton6.setText("Thống kê");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        BacktoHomePagebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/home (1).png"))); // NOI18N
        BacktoHomePagebtn.setText("  Back to HomePage");
        BacktoHomePagebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoHomePagebtnActionPerformed(evt);
            }
        });

        delNhanKhaubtn.setBackground(new java.awt.Color(255, 255, 255));
        delNhanKhaubtn.setForeground(new java.awt.Color(102, 102, 255));
        delNhanKhaubtn.setText("Xóa Nhân Khẩu");
        delNhanKhaubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delNhanKhaubtnActionPerformed(evt);
            }
        });

        editNhanKhaubtn.setBackground(new java.awt.Color(255, 255, 255));
        editNhanKhaubtn.setForeground(new java.awt.Color(102, 102, 255));
        editNhanKhaubtn.setText("Cập nhật Nhân Khẩu");
        editNhanKhaubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNhanKhaubtnActionPerformed(evt);
            }
        });

        addNhanKhaubtn.setBackground(new java.awt.Color(255, 255, 255));
        addNhanKhaubtn.setForeground(new java.awt.Color(102, 102, 255));
        addNhanKhaubtn.setText("Thêm Nhân Khẩu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BacktoHomePagebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editNhanKhaubtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addNhanKhaubtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delNhanKhaubtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(BacktoHomePagebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(addNhanKhaubtn)
                .addGap(18, 18, 18)
                .addComponent(delNhanKhaubtn)
                .addGap(18, 18, 18)
                .addComponent(editNhanKhaubtn)
                .addGap(0, 375, Short.MAX_VALUE))
        );

        tfSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfSearchCaretUpdate(evt);
            }
        });
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        TableNK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Khẩu", "Tên Nhân Khẩu", "Tuổi", "CMND", "SĐT", "Mã Hộ khẩu", "Quan hệ chủ hộ"
            }
        ));
        TableNK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableNK);
        if (TableNK.getColumnModel().getColumnCount() > 0) {
            TableNK.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel1.setText("Tìm kiếm theo tên: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delNhanKhaubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delNhanKhaubtnActionPerformed
        // TODO add your handling code here:
        if(strID.equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhân khẩu để xóa");
        }else{
            if(dao.delNhanKhau(Integer.parseInt(strID))>0)
            {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            fillTable();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_delNhanKhaubtnActionPerformed

    private void BacktoHomePagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoHomePagebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BacktoHomePagebtnActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void editNhanKhaubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNhanKhaubtnActionPerformed
        // TODO add your handling code here:
        selectedIndex = TableNK.getSelectedRow();
        if(dao.getAll().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập thêm nhân khẩu rồi sửa");
        }
        else if(selectedIndex  == -1){
            JOptionPane.showMessageDialog(rootPane,"Hãy chọn Nhân Khẩu cần sửa");
        }
        else{
            EditNhanKhauView edit = new EditNhanKhauView();
            edit.setEditData(dao.getAll().get(selectedIndex));
            edit.setVisible(true);
            this.dispose();
                    
       }
        
    }//GEN-LAST:event_editNhanKhaubtnActionPerformed

    private void TableNKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNKMouseClicked
        // TODO add your handling code here:
        int position = TableNK.rowAtPoint(evt.getPoint());
        strID = TableNK.getValueAt(position, 0).toString();

    }//GEN-LAST:event_TableNKMouseClicked

    private void tfSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfSearchCaretUpdate
        // TODO add your handling code here:
       strFind = tfSearch.getText();
       fillTable();
    }//GEN-LAST:event_tfSearchCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanKhauView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BacktoHomePagebtn;
    private javax.swing.JTable TableNK;
    private javax.swing.JButton addNhanKhaubtn;
    private javax.swing.JButton delNhanKhaubtn;
    private javax.swing.JButton editNhanKhaubtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
      if(e.getSource().equals(addNhanKhaubtn))
      {
          addNhanKhauclick();
      }
      else if(e.getSource().equals(delNhanKhaubtn))
      {    
          delNhanKhauclick();
      }
    
      else if(e.getSource().equals(BacktoHomePagebtn))
      {
          backtoHomePageClick();
      }
          
    }
    
    public void addNhanKhauclick(){
        new AddNhanKhauView().setVisible(true);
        this.dispose();
    }
    
    public void delNhanKhauclick(){
        
    }
   
    
    public void backtoHomePageClick(){
        new TrangChuView().setVisible(true);
        this.dispose();
    }
}
