/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ThinkKING
 */
public class TrangChuView extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form TrangChuView
     */
    public TrangChuView() {
        initComponents();
        setTitle("Homepage");
        setLocationRelativeTo(null);
        NhanKhaubtn.addActionListener(this);
        HoKhaubtn.addActionListener(this);
        KhoanPhibtn.addActionListener(this);
        DongPhibtn.addActionListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NhanKhaubtn = new javax.swing.JButton();
        HoKhaubtn = new javax.swing.JButton();
        KhoanPhibtn = new javax.swing.JButton();
        DongPhibtn = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 36)); // NOI18N
        jLabel1.setText("HomePage");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QLNhanKhau12");

        NhanKhaubtn.setBackground(new java.awt.Color(0, 153, 255));
        NhanKhaubtn.setForeground(new java.awt.Color(255, 255, 255));
        NhanKhaubtn.setText("Nhân Khẩu");
        NhanKhaubtn.setBorder(null);
        NhanKhaubtn.setBorderPainted(false);

        HoKhaubtn.setBackground(new java.awt.Color(0, 153, 255));
        HoKhaubtn.setForeground(new java.awt.Color(255, 255, 255));
        HoKhaubtn.setText("Hộ Khẩu");
        HoKhaubtn.setBorderPainted(false);
        HoKhaubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoKhaubtnActionPerformed(evt);
            }
        });

        KhoanPhibtn.setBackground(new java.awt.Color(0, 153, 255));
        KhoanPhibtn.setForeground(new java.awt.Color(255, 255, 255));
        KhoanPhibtn.setText("Khoản phí");
        KhoanPhibtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        KhoanPhibtn.setBorderPainted(false);
        KhoanPhibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhoanPhibtnActionPerformed(evt);
            }
        });

        DongPhibtn.setBackground(new java.awt.Color(0, 153, 255));
        DongPhibtn.setForeground(new java.awt.Color(255, 255, 255));
        DongPhibtn.setText("Đóng phí");
        DongPhibtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DongPhibtn.setBorderPainted(false);
        DongPhibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DongPhibtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DongPhibtn, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(KhoanPhibtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HoKhaubtn, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                        .addComponent(NhanKhaubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(NhanKhaubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(HoKhaubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(KhoanPhibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(DongPhibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DongPhibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DongPhibtnActionPerformed
        // TODO add your handling code here:
        new NopTienView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DongPhibtnActionPerformed

    private void HoKhaubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoKhaubtnActionPerformed
        // TODO add your handling code here:
        new HoKhauView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HoKhaubtnActionPerformed

    private void KhoanPhibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhoanPhibtnActionPerformed
        // TODO add your handling code here:
        new KhoanThuView().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_KhoanPhibtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DongPhibtn;
    private javax.swing.JButton HoKhaubtn;
    private javax.swing.JButton KhoanPhibtn;
    private javax.swing.JButton NhanKhaubtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       if(e.getSource().equals(NhanKhaubtn))
       {
           NhanKhaubtnClick();
       }
       else if(e.getSource().equals(HoKhaubtn))
       {
           HoKhaubtnClick();
       }
       else if(e.getSource().equals(KhoanPhibtn))
       {
           KhoanPhibtnClick();
       }
       else if(e.getSource().equals(DongPhibtn))
       {
           DongPhibtnClick();
       }
    
        
    }
    
    public void NhanKhaubtnClick(){
        new NhanKhauView().setVisible(true);
        this.dispose();
    }
    public void HoKhaubtnClick(){
        
    }
    
    public void KhoanPhibtnClick(){
        
    }
    public void DongPhibtnClick(){
        
    }
   
}
